service:
  name: marcoLastUpdatedTime

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-2'}
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudformation:describeStacks"
      Resource: "*"

functions:
  getStackLastUpdatedTime:
    handler: handler.getStackLastUpdatedTime

resources:
  - ${file(resources/macro.yml)}
